language: node_js

node_js:
  - stable
  - 8
  - 6


sudo: required

services:
  - docker

env:
  - POSTGRES_Skip=0 POSTGRES_Host=localhost POSTGRES_Port=5432 POSTGRES_Username=postgres POSTGRES_Password=!Passw0rd POSTGRES_Database=typeorm_mg POSTGRES_SSL=0  MYSQL_Skip=0 MYSQL_Host=localhost MYSQL_Port=3306 MYSQL_Username=root MYSQL_Password=!Passw0rd MYSQL_Database=typeorm_mg MYSQL_SSL=1  MARIADB_Skip=0 MARIADB_Host=localhost MARIADB_Port=3307 MARIADB_Username=root MARIADB_Password=!Passw0rd MARIADB_Database=typeorm_mg MARIADB_SSL=0 

before_install:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose up -d


before_script:
  - npm run typings-install
  - npm link typescript
  - tsc

