version: '2'
services:

  # mysql
  mysql:
    image: "mysql:5.7.19"
    container_name: "typeorm-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "!Passw0rd"

  # mariadb
  mariadb:
    image: "mariadb:10.2.9"
    container_name: "typeorm-mariadb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "!Passw0rd"

  # postgres
  postgres:
    image: "postgres:10.0"
    container_name: "typeorm-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "!Passw0rd"

  # # mssql
  # mssql:
  #   image: "microsoft/mssql-server-linux:2017-GA"
  #   container_name: "typeorm-mssql"
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     SA_PASSWORD: "!Passw0rd"
  